package com.remi.engine.domain;

public enum RejectReason {
  NOT_YOUR_TURN, WRONG_PHASE, GAME_CLOSED,
  STOCK_EMPTY, DISCARD_EMPTY,
  CANNOT_TAKE_OPENING_PIECE, CANNOT_BREAK_LINE, BREAK_REQUIRES_ETALAT,
  PIECE_NOT_IN_HAND, INVALID_MELD,
  FIRST_MELD_TOO_FEW_POINTS, FIRST_MELD_NEEDS_SUITE_OR_1S,
  MUST_USE_TAKEN_PIECE, NOT_ETALAT, INVALID_LAYOFF, HAND_TOO_FULL_TO_DISCARD
}
